### ISSUE TITLE
The steer shaking or vibrating on high sensitivity 

### ISSUE THREAD

**Issue by Artist128** [surendra019/virtual-steering-addon-godot#1]
The steering is shaking on high sensitivity. It's not feels smooth feels laggy please fix this
https://github.com/user-attachments/assets/1cc370b8-701c-4ffa-809d-09be872d720d

**Comment by surendra019** [comment]
Noted your issue, fix this in the next update!

**Comment by surendra019** [comment]
Get the latest from the releases section, make sure to read the note there.
